language: java
before_install: mvn install -DskipTests=true -DfinalName=dictionary-matcher-factory-gui-$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: ZHT5w7ygaLmDadlS/1GEu0T6UUl6me+sO1pL1FPWTMJkEqmEfh+FSQwTvo4Big8g7wEIfYWOi425d2JirN5Gx6YmxkKgYTZvFgaQbP32ouCi2pwJNDKSAJ76tHFUX4Sa/WUCMI1XcbeBp8Gx+MInEEOYGzH1SaH4pLNdeqdA8W8=
  file: target/dictionary-matcher-factory-gui-$TRAVIS_TAG-jar-with-dependencies.jar
  on:
    repo: fusepoolP3/p3-dictionary-matcher-factory-gui
    tags: true
    all_branches: true
